MAIN-199: Тесты сервиса сертификатов
onied/main pull request #105
Opened 2024-10-09 09:58 UTC by iigaz

На этом микросервисе уже были тесты некоторых контроллеров и сервисов, я добавил тесты на контроллер и сервис сертификатов, и один "пустой" тест который покрывает все модули (модули не содержат никакую логику, и этот тест просто помечает их всех покрытыми).

87% покрытие всех файлов итого, я не покрывал consumerы и `main.ts`.

2024-10-13 23:01 UTC, antonborisov571 requested changes

2024-10-14 12:55 UTC, iigaz commented on backend/certificates/src/certificate/certificate.service.spec.ts
>    });
Нет, так как в случае с ручным прописыванием моков можно более точечно настроить объекты.

2024-10-14 12:55 UTC, iigaz commented on backend/certificates/src/certificate/certificate.service.spec.ts
> +      };
> Нет, так как в случае с ручным прописыванием моков можно более точечно настроить объекты.

2024-10-14 13:00 UTC, iigaz commented
В целом идея понятна, и можно сделать функции с кастомизацией моков, но пока что усилия, требуемые на то, чтобы определить где что изменяется в моках, не оправдывают замену их на функцию, по моему мнению. В конце концов тесты должны никак не зависеть друг от друга, а здесь появляется косвенная зависимость (нужно изменить поле, изначально не прописанное в функции-создателе, только в одном тесте -> добавляем в функцию -> теперь нам нужно добавить этот аргумент в каждый тест)

2024-10-14 13:18 UTC, antonborisov571 commented on backend/certificates/src/certificate/certificate.service.spec.ts
>    });
Хорошо)

Позже он увидит тесты репозиториев👀
Там буквально везде используется метод ProduceTestData, который генерирует данные для тестов в избежании дублирования кода

2024-10-14 13:22 UTC, merged