MAIN-207-208: Бэкенд чата
onied/main pull request #115
Opened 2024-10-25 16:59 UTC by antonborisov571

2024-10-26 08:31 UTC, iigaz commented
> И ещё, должен ли создаваться чат если его просит пользователь?

Я уже сделал в своем PR (соседнем), чтобы чат создавался при первом сообщении. Еще не смотрел как у тебя реализовано, но я предполагаю что возвратится 404 и фронт корректно это обработает (например, надписью "чат пуст" или "введите сообщение, чтобы начать").

2024-10-26 08:32 UTC, iigaz commented
При первом запросе к чату тоже можно, но тогда просто будет куча пустых чатов. Если у тебя уже так сделано, то пока не переделывай, если не сделано, то не делай.

2024-10-26 08:34 UTC, iigaz commented
Проверю не позже понедельника, не обещаю что раньше

2024-10-26 08:43 UTC, iigaz commented
> класс для ошибок Http не работал (я как понял это работает только на .NET framework)

Ты прав.

> создал свой и создал middleware. Отнаследовал от HttpResponseException(от своего класса) ещё классы для ошибок, чтобы в конструктор передавать только текст ошибки. Получилось по типу NotFoundException(message)

Судя по всему это то, как большинство и делают в современном аспнете.

2024-10-26 08:47 UTC, iigaz commented on backend/Onied/Support/Support/Support.csproj
> +    </ItemGroup>
Убери пустую папку

2024-10-26 09:23 UTC, iigaz commented on backend/Onied/Support/Support/Middlewares/ExceptionMiddleware.cs
> +            await context.Response.WriteAsJsonAsync(new { message = exception.Message });
Вот так точно лучше не делать, для этого есть специальный middleware который ловит остальные ошибки и показывает их, если Environment = Debug, и просто говорит 500 в ином случае. Показывать ошибки вне зависимости от ситуации пользователю не очень хорошо.

2024-10-26 09:24 UTC, iigaz commented on backend/Onied/Support/Support/Middlewares/ExceptionMiddleware.cs
> +            await context.Response.WriteAsJsonAsync(new { message = exception.Message });
Мое предложение: (не проверял, и не советую принимать его без проверки)

```suggestion
            throw exception;
```

2024-10-26 09:34 UTC, iigaz commented on backend/Onied/Support/Support/Middlewares/ExceptionMiddleware.cs
> +            await context.Response.WriteAsJsonAsync(exception.Message);
В одном

```json
{
   "message": "error"
}
```

в другом

```json
"error"
```

Неконсистентность.

А еще, `context.Response.ContentType` не нужно проставлять, так как его автоматически должна проставить следующая же строчка.

Во-первых, нужно добавить `"message":` во второй обработчик.

Во-вторых, и это уже чисто мое пожелание и не требует выполнения, вместо `message` можно использовать `detail`, так как именно оно возвращается стандартными библиотеками asp.net core (identity возвращает ошибочный ответ с 4-мя полями: тип ответа `type` - ссылка на стандарт, заголовок `title` - название кода ошибки (Not Found, Bad Request, Unauthorized, `status` - сам код ошибки, `detail` - собственно сообщение ошибки. Из этих полей реально важным является только Detail, остальные можно получить из кода ответа в заголовках). Но так как у нас и так уже зоопарк различных ответов, я на это обращать внимание сильно не буду.

2024-10-26 09:44 UTC, iigaz commented on backend/Onied/Support/Support/Services/SupportService.cs
> +        await authorizationSupportUserService.AuthorizeSupportUser(userId);
Мне кажется лучше вынести авторизацию в декоратор для контроллера и проверять через middleware (authorization policy и requirement, или authorization filter)

Пример первого есть в моей соседней ветке, там тоже авторизация пользователей, но она специфична для signalr хаба, можно адаптировать.

Пример второго должен быть в Courses.

2024-10-26 09:56 UTC, iigaz commented on backend/Onied/Support/Support/Middlewares/ExceptionMiddleware.cs
> +        }
```suggestion
```

Вот так мне советует rider

2024-10-26 10:27 UTC, iigaz commented on backend/Onied/Support/Support/Services/ChatService.cs
> +            throw new BadRequestException("The chat has not yet been created for this user");
No chat found, но при этом возвращаем badrequest. Мне кажется логичнее было бы 404.
```suggestion
            logger.LogWarning("No chat found for user ID: {UserId}. The chat has not yet been created", userId);
            throw new NotFoundException("The chat has not yet been created for this user");
```

2024-10-26 10:34 UTC, iigaz commented on backend/Onied/Support/Support/Services/ChatService.cs
> +        }
Эта проверка не позволяет получить историю конкретного чата собственно того оператора, который на нее назначен. Более того, чаты (как я писал) не являются приватной информацией между операторами. Поэтому я предлагаю одно из двух:

1. Добавить условие `chat.SupportId != userId`.
2. 

```suggestion
```

Единственное, написать сообщение в уже занятый чат оператор не должен иметь возможность. Но посмотреть - не вижу почему нет (оставить это условие тоже можно, так как не было описано в доке что любой оператор должен получить доступ).

2024-10-26 10:50 UTC, iigaz commented on backend/Onied/Support/Support/Profiles/AppMappingProfile.cs
> +                opt => opt.MapFrom(src => src.Chat.Support == null ? (int?)null : src.Chat.Support.Number))
Во всех сообщениях supportNumber будет зависеть от привязанного сотрудника. Это неверно. Здесь исправление, которое поставит number только тогда, когда отправитель - текущий оператор.

```suggestion
            .ForMember(dest => dest.SupportNumber,
                opt => opt.MapFrom(src =>
                    src.Chat.Support == null ? (int?)null :
                    src.Chat.SupportId == src.UserId ? src.Chat.Support.Number : null))
```

Это примерно то, что я сделал в своих маппингах в своем pr. Но есть проблема: Это тоже неверно. Старые операторы будут отображаться как null.

Скорее всего, самым простым решением будет сохранять номер оператора в БД, если прямо соответствовать требованиям. Я не учел этого когда писал их.

2024-10-26 10:51 UTC, iigaz commented on backend/Onied/Support/Support/Profiles/AppMappingProfile.cs
> +                opt => opt.MapFrom(src => src.Chat.Support == null ? (int?)null : src.Chat.Support.Number))
```suggestion
            .ForMember(dest => dest.SupportNumber,
                opt => opt.MapFrom(src => src.Chat.Support == null ? (int?)null :
                    src.Chat.SupportId == src.UserId ? src.Chat.Support.Number : null))
```

Это предложение неверно, см. предыдущее сообщение. Но оставляю исправление чтобы не забыл

2024-10-26 10:54 UTC, iigaz commented
TODO (тебе): нужно добавить `int SupportNumber?` в базу данных, в таблицу `Messages`, потому что иначе не узнать, какой именно оператор оставлял конкретное сообщение в предыдущих сессиях.

2024-10-26 10:56 UTC, iigaz requested changes
Написал все, что не ускользнуло из моего внимания. Ожидаю исправлений.

2024-10-26 10:59 UTC, iigaz commented
> TODO (тебе): нужно добавить `int? SupportNumber` в базу данных, в таблицу `Messages`, потому что иначе не узнать, какой именно оператор оставлял конкретное сообщение в предыдущих сессиях, не перебирая все сообщения

Ну кстати еще можно сформулировать кастомный запрос к БД, в котором брать номер сотрудника из UserId если сотрудник есть. Так будет даже намного лучше, чем вариант выше.

2024-10-28 14:31 UTC, iigaz commented on backend/Onied/Support/Support/Support.csproj
> +      <ProjectReference Include="..\..\Common\Common.Validation\Common.Validation.csproj" />
Быстрый вопрос: а где он используется? Я не могу найти в изменениях упоминание Common не считая этого файла

2024-10-28 14:33 UTC, antonborisov571 commented on backend/Onied/Support/Support/Support.csproj
> +      <ProjectReference Include="..\..\Common\Common.Validation\Common.Validation.csproj" />
Нигде, я сначала юзанул, а потом убрал

2024-10-28 14:47 UTC, iigaz approved these changes

2024-10-28 14:47 UTC, merged